### PR TITLE
Update Baidu, DataScienceToolkit, IGNOpenLS, IpInfo, OGDViennaAustria and OIORest providers for v3

### PR DESCRIPTION
**Pull request by romainneutron**
Some providers have not been updated:
 - IpGeoBase
 - GeocoderCA
 - GeocoderUS
 - Geocodio
 - Naver
 - Telize

these have fixtures that fails (might be already failing in version 2.0) and needs investigation

### CODE REVIEW

**Comment by romainneutron** [comment]
I've updated `.travis` as done in #25 . Tests are now green

**Comment by willdurand** [comment]
That's awesome! Thank you for that.

I cannot remember why the `script` line in `.travis.yml` specifies a single test, but anyway, thanks for your work.

**Comment by willdurand** [comment]
Also, did you see #27 ?

**Comment by romainneutron** [comment]
Yep I've seen #27. About the travis file, it comes from #25 . The contributor tweaked the travis file because some tests are failing.

**Comment by romainneutron** [comment]
I can take some time on them, progressively. About #27, I've seen that, and my work has been inspired by your PR, changes are in the same way

**Comment by willdurand** [comment]
:+1:

**Comment by willdurand** [comment]
thanks for this first batch!

**Pull request merged**
